# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: FAJ Impressionen
email: luca.derrez@yahoo.de
handy: +49 163 9260115
street: Amselweg 20
village: 72663 Großbettlingen
description: Ein Bericht über mein Freiwilligendienst in Neuseeland, Informationen über mich und Informationen für Mitglieder meines Unterstüzerkreises.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
